version: "3.7"
services:
  base:
    # env_file:
    #   - prod.env
    build:
      dockerfile: ./Dockerfile.development
      context: .
    # depends_on:
    #   - mariadb
    #   - mongo
    networks:
      - proxy
  grpc:
    extends:
      service: base
    command: go run ./grpc/cmd main.go
    environment:
      - PORT=50051
    ports:
      - 50051:50051
    restart: always
  http:
    extends:
      service: base
    command: go run ./http/cmd main.go
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    restart: always
networks:
  proxy:
    driver: bridge